name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Build and push the image
        run: |
          docker login --username prithvia28 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/prithvia28/arithmetic-service:latest --file Dockerfile .  
          docker push ghcr.io/prithvia28/arithmetic-service:latest
      
      - name: Publish the image to github container registry
        run: |
          docker login --username practicum16crpithvi --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum16crpithvi.azurecr.io
          docker tag ghcr.io/prithvia28/arithmetic-service:latest practicum16crpithvi.azurecr.io/arithmetic-service:latest
          docker push practicum16crpithvi.azurecr.io/arithmetic-service:latest
